name: Build Flutter APK and Upload Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Use an Ubuntu VM for building

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up Java SDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Adjust based on your project's requirements

    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.2' # Adjust based on your project's requirements

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --no-run

    - name: Upload APK as build artifact
      uses: actions/upload-artifact@v2
      with:
        path: build/app/outputs/flutter/release/app-release.apk
